### PR TITLE
Files to support an Octave-Forge package

### PR DESCRIPTION
**Pull request by cbm755**
This requires a tarball with files in special places.  Add a
    script that makes such a tarball.  Add the various support files.

### CODE REVIEW

**Comment by cbm755** [comment]
@catch22 I'd like to submit this as an Octave-Forge package.  This makes installation easily from within Octave (`pkg install -forge doctest`).

What do you think?  We need to start versioning it, have releases, etc.

If you think this is a good idea, could I request push access, e.g., so I could push tags for releases.  (for actual changes I will not push directly but continue sending PRs).

I would also need to host a git clone on sourceforge, but I can handle that.

**Comment by catch22** [comment]
That sounds good to me. I've given you push access; let me know if things work.

Maybe it would be good to document the development workflow in a wiki entry (e.g., what needs to be done upon an octave-forge release etc. - even when you will be the one in charge for publishing the package on octave-forge at this point).

Also, what do you think about having the `NEWS` file in the root folder (as it seems useful for all users) and just copy it to `octaveforge_pkg` as part of the makefile.

**Comment by cbm755** [comment]
> what do you think about having the NEWS file in the root folder

Sounds good to me.

The whole `octaveforge_pkg` subdir was a bit of hack to be minimally invasive for Matlab users: there may be other ways.  Also, other OctaveForge maintainers may not be keen on this being too different from the other packages.  We'll see.  I'd prefer to avoid forking.

Either way, +1 for documenting the workflow.  I will do.

**Comment by catch22** [comment]
I moved most of the files in `octaveforge_pkg` to the root directory (and added the shell script to the makefile -- I hope that's ok). If it is more in line with OctaveForge then we can also move the `DESCRIPTION` file to the root directory.

**Pull request merged**
